[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "python-dotenv>=1.1.1",
    "flask>=2.1.1",
    "waitress>=2.1.2",
    "aiohttp>=3.12.13",
]
